name: Deploy CBS quotation API to development environment

on:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: cbs-quotation-api-dev
  AZURE_RG: ks-api-dev 
  IMAGE_NAME: cbs-quotation-api-dev 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      run: echo ${{ secrets.REGISTRY_PASSWORD_DEV }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }} -u ${{ secrets.REGISTRY_USERNAME_DEV }} --password-stdin

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }}/${{ env.IMAGE_NAME }}:latest

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.REGISTRY_LOGIN_SERVER_DEV }}/${{ env.IMAGE_NAME }}:latest
        
    - name: Azure logout
      run: |
        az logout
